### ISSUE TITLE
Help command not functioning

### ISSUE THREAD

**Issue by plerpsandplerps** [AlexanderLindsay/PredictionMarketBot#5]
![image](https://user-images.githubusercontent.com/62353692/130859388-69bc37e3-8726-44cd-8c9c-7702f6b62c4c.png)

Getting an unknown command error when I try to run the help command.

**Comment by AlexanderLindsay** [comment]
This is probably an issue with changes to the [Discord.Net](https://docs.stillu.cc/index.html) code which I used for this. If you want to fix this it would mean updating to the latest version of the Discord.Net packages and making the code changes that may or may not require. I don't think I am going to do that tbh. Sorry.
